[package]
name = "thalassophobia"
version = "0.1.0"
edition = "2021"
authors = ["veritius <veritiusgaming@gmail.com>"]

[dependencies.bevy]
version = "0.12"

[dependencies.bevy_rapier3d]
version = "0.22.0"
features = ["simd-nightly", "parallel"]