[package]
name = "thalassophobia_client"
version = "0.1.0"
edition = "2021"
authors = ["veritius <veritiusgaming@gmail.com>"]

[dependencies.shared]
package = "thalassophobia_shared"
path = "../shared"
features = ["render"]

[dependencies.server]
package = "thalassophobia_server"
path = "../server"
optional = true

[dependencies.bevy_editor_pls]
version = "0.8"
optional = true

[features]
default = ["listen", "editor"]
multiplayer = ["shared/multiplayer"]
listen = ["multiplayer", "dep:server"]
editor = ["dep:bevy_editor_pls"]