[package]
name = "thalassophobia_dedi"
version = "0.1.0"
edition = "2021"
authors = ["veritius <veritiusgaming@gmail.com>"]

[dependencies.shared]
package = "thalassophobia_shared"
path = "../shared"

[dependencies.server]
package = "thalassophobia_server"
path = "../server"