[package]
name = "thalassophobia_server"
version = "0.1.0"
edition = "2021"
authors = ["veritius <veritiusgaming@gmail.com>"]

[[bin]]
name = "headless"

[dependencies.shared]
package = "thalassophobia_shared"
path = "../shared"
features = ["multiplayer"]