[package]
name = "thalassophobia_shared"
version = "0.1.0"
edition = "2021"
authors = ["veritius <veritiusgaming@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies.bevy]
version = "0.13"
default-features = false
features = [
    "bevy_asset",
    "bevy_scene",
]

[dependencies.bevy_rapier3d]
version = "0.25"
features = ["parallel"]

[dependencies.leafwing-input-manager]
version = "0.13"

[dependencies.bevy_stardust]
version = "0.5"
optional = true

[features]
default = ["bevy_dylib"]
multiplayer = ["bevy_stardust"]
phys_debug = ["bevy_rapier3d/debug-render"]
bevy_default = ["bevy/default"]
bevy_dylib = ["bevy/dynamic_linking"]
